### ISSUE TITLE
Pab applicatios long start time

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus-apps#145]
Pab application on testnet is way to slow, every time when I need to fix something, rebuild my bultin contracts and run pab again it takes 20-30 minutes to sync with node,
untill I get to `Current block: 366710. Current slot: 43453153 `

Are there option to update contracts without restart and resync data,
Can we cache node data so we do not have to sync on each start?

If I need to test `Cardano Wallet-Pab` integration can I connect to mock node?
What options do you propose to speed up development?

**Comment by volodyad** [comment]
Seems when I start Mock-mode, it starts MockWallet client , could you please confirm that there is will not work - start test node and provide url to running cardano-wallet 
```
walletServerConfig:
  baseUrl: http://localhost:8090
  wallet:
    getWallet: 1

nodeServerConfig:
  mscBaseUrl: http://localhost:9082
  mscSocketPath: ./node-server.sock
  mscKeptBlocks: 100
  mscNetworkId: "1097911063" # Testnet network ID (main net = empty string)
  mscSlotConfig:
    scSlotZeroTime: 1596059091000 # Wednesday, July 29, 2020 21:44:51 - shelley launch time in milliseconds
    scSlotLength: 1000 # In milliseconds
  mscFeeConfig:
    fcConstantFee:
      getLovelace: 10 # Constant fee per transaction in lovelace
    fcScriptsFeeFactor: 1.0 # Factor by which to multiply size-dependent scripts fee in lovelace
  mscInitialTxWallets:
    - getWallet: 1
    - getWallet: 2
    - getWallet: 3
  mscNodeMode: MockNode
```
