### ISSUE TITLE
Control.Monad.Freer.Extras.Beam.Postgres.DbConfig(DbConfig) failed, key \"dbConfigMarconiFile\" not found

### ISSUE THREAD

**Issue by SpiersZ** [input-output-hk/plutus-apps#895]
### Summary

I tried to switch to postgres, according to https://github.com/input-output-hk/plutus-apps/pull/713.
But when starting, it prompts `AesonException "Error in $.postgresDB: parsing Control.Monad.Freer.Extras.Beam.Postgres.DbConfig(DbConfig) failed, key \"dbConfigMarconiFile\" not found"`
What does this dbConfigMarconiFile need to pass in?

### Steps to reproduce the behavior

1. Update database configuration, template for reference: https://github.com/input-output-hk/plutus-apps/blob/main/plutus-pab-executables/plutus-pab.yaml.sample#L7
```
 postgresDB:
     dbConfigUser: postgres
     dbConfigPass: postgres123
     dbConfigHost: 127.0.0.1
     dbConfigPort: 5432
     dbConfigDatabase: pab
     dbConfigPoolSize: 20
```
2.  exec `cabal run pab-swap -- all-servers --config ./swap/plutus-pab.yaml`

### Actual Result

pab-swap: AesonException "Error in $.postgresDB: parsing Control.Monad.Freer.Extras.Beam.Postgres.DbConfig(DbConfig) failed, key \"dbConfigMarconiFile\" not found

### Expected Result

Running

### System info

OS: Ubuntu 20.04
